object frmConfirmBillNo: TfrmConfirmBillNo
  Left = 300
  Top = 107
  Width = 380
  Height = 175
  BorderIcons = [biSystemMenu]
  Caption = #3618#3639#3609#3618#3633#3609#3610#3633#3609#3607#3638#3585#3619#3633#3610#3610#3619#3636#3592#3634#3588
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  OnKeyDown = FormKeyDown
  PixelsPerInch = 96
  TextHeight = 13
  object pnTop: TRzPanel
    Left = 0
    Top = 0
    Width = 372
    Height = 148
    Align = alClient
    BorderInner = fsFlat
    BorderOuter = fsGroove
    TabOrder = 0
    object Label1: TLabel
      Left = 83
      Top = 13
      Width = 104
      Height = 22
      AutoSize = False
      Caption = '  '#3648#3621#3586#3607#3637#3656#3610#3636#3621' '
      Color = clGray
      Font.Charset = THAI_CHARSET
      Font.Color = clWhite
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object lbBillNo: TLabel
      Left = 83
      Top = 35
      Width = 222
      Height = 46
      Alignment = taCenter
      AutoSize = False
      Caption = '0000001'
      Color = clBlack
      Font.Charset = THAI_CHARSET
      Font.Color = clYellow
      Font.Height = -29
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Layout = tlCenter
    end
    object btnOK: TRzBitBtn
      Left = 189
      Top = 106
      Width = 77
      Height = 27
      Default = True
      Caption = 'OK'
      Color = 16747546
      Font.Charset = THAI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      HotTrack = True
      ParentFont = False
      TabOrder = 0
      TabStop = False
      OnClick = btnOKClick
    end
    object btnCancel: TRzBitBtn
      Left = 269
      Top = 106
      Width = 77
      Height = 27
      Caption = 'Cancel'
      Color = 16747546
      Font.Charset = THAI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      HotTrack = True
      ParentFont = False
      TabOrder = 1
      TabStop = False
      OnClick = btnCancelClick
    end
  end
end
