object frmEditItem: TfrmEditItem
  Left = 444
  Top = 236
  Width = 521
  Height = 162
  BorderIcons = [biSystemMenu]
  Caption = #3649#3585#3657#3652#3586#3619#3634#3618#3585#3634#3619
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  OnKeyDown = FormKeyDown
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object pnClientContainer: TPanel
    Left = 0
    Top = 0
    Width = 513
    Height = 135
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 0
    object pnTop: TRzPanel
      Left = 0
      Top = 0
      Width = 513
      Height = 135
      Align = alClient
      BorderInner = fsFlat
      BorderOuter = fsGroove
      TabOrder = 0
      object Label3: TLabel
        Left = 9
        Top = 8
        Width = 73
        Height = 22
        AutoSize = False
        Caption = ' '#3623#3633#3605#3606#3640#3611#3619#3632#3626#3591#3588#3660
        Color = clSilver
        Font.Charset = THAI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        Layout = tlCenter
      end
      object Label11: TLabel
        Left = 9
        Top = 32
        Width = 73
        Height = 22
        AutoSize = False
        Caption = ' '#3585#3629#3591#3607#3640#3609
        Color = clSilver
        Font.Charset = THAI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        Layout = tlCenter
      end
      object Label1: TLabel
        Left = 9
        Top = 64
        Width = 73
        Height = 22
        AutoSize = False
        Caption = ' '#3592#3635#3609#3623#3609#3648#3591#3636#3609
        Color = clSilver
        Font.Charset = THAI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        Layout = tlCenter
      end
      object edObjtiveName: TRzEdit
        Left = 85
        Top = 8
        Width = 416
        Height = 22
        Color = 15794175
        Ctl3D = False
        Font.Charset = THAI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        FocusColor = 16766975
        ParentCtl3D = False
        ParentFont = False
        TabOrder = 0
      end
      object edFundName: TRzEdit
        Left = 85
        Top = 32
        Width = 416
        Height = 22
        Color = 15794175
        Ctl3D = False
        Font.Charset = THAI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        FocusColor = 16766975
        ParentCtl3D = False
        ParentFont = False
        TabOrder = 1
      end
      object edAmount: TRzNumericEdit
        Left = 84
        Top = 62
        Width = 189
        Height = 24
        Font.Charset = THAI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        FrameVisible = True
        ParentFont = False
        TabOrder = 2
        OnKeyDown = edAmountKeyDown
        DisplayFormat = ',0;(,0)'
      end
      object btnOK: TRzBitBtn
        Left = 329
        Top = 99
        Width = 88
        Height = 27
        Caption = 'OK'
        Color = 16753994
        Font.Charset = THAI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        HotTrack = True
        ParentFont = False
        TabOrder = 3
        OnClick = btnOKClick
      end
      object btnCancel: TRzBitBtn
        Left = 419
        Top = 99
        Width = 88
        Height = 27
        Caption = 'Cancel'
        Color = 16753994
        Font.Charset = THAI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        HotTrack = True
        ParentFont = False
        TabOrder = 4
        OnClick = btnCancelClick
      end
    end
  end
end
